spring.application.name=pharma-notification-service

server.port=${PORT:8080}

# MongoDB

spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}

# Other microservice URLs

billing.service.url=${BILLING_SERVICE_URL}
inventory.service.url=${INVENTORY_SERVICE_URL}
auth.service.url=${AUTH_SERVICE_URL}

# JWT

jwt.secret=${JWT_SECRET}
jwt.expiration=86400000
